const SET_USERS_LOADING = 'USERS/SET_USERS_LOADING';
const SET_USERS_ERROR = 'USERS/SET_USERS_ERROR';
const SET_USERS = 'USERS/SET_USERS';
const SET_NEXT_URL = 'USERS/SET_NEXT_URL';

export default {
  SET_USERS_LOADING,
  SET_USERS_ERROR,
  SET_USERS,
  SET_NEXT_URL,
};
